key-store:
    micronaut:
        ssl:
            key-store:
                path: classpath:keystore.p12
                password: _encrypted_

micronaut:
    ssl:
        enabled: true
        key-store:
            __workaround_: "Required for the configuration bean replacement"
