custom:
    path: classpath:keystore.p12
    password: _encrypted_

key-store:
    custom:
        path: classpath:keystore.p12
        password: _encrypted_

micronaut:
    application:
        name: micronautSandbox

    ssl:
        enabled: true
        key-store:
            custom:
                path: classpath:keystore.p12
                password: _encrypted_
